CONFIG_LOG=y

CONFIG_SERIAL=y
CONFIG_UART_ASYNC_API=y
CONFIG_UART_USE_RUNTIME_CONFIGURE=y
# CONFIG_UART_INTERRUPT_DRIVEN=y

CONFIG_CAN=y

CONFIG_STM32_ENABLE_DEBUG_SLEEP_STOP=y

CONFIG_DEBUG_OPTIMIZATIONS=y
# CONFIG_NO_OPTIMIZATIONS=y

CONFIG_MAIN_STACK_SIZE=4096
